name: Build Web Release

on:
  push:
    branches:
      - main

jobs:
  build-web:
    name: Build Web Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1' # Specify the required Flutter version

      # Step 3: Navigate to the Flutter app directory
      - name: Navigate to Flutter App Directory
        working-directory: Applicatie/Cross_Platform_Groep2
        run: |
          echo "::group::Navigating to Flutter App Directory"
          echo "Navigating to Flutter app directory"
          echo "::endgroup::"

      # Step 4: Install dependencies
      - name: Install Dependencies
        working-directory: Applicatie/Cross_Platform_Groep2
        run: |
          echo "::group::Installing Dependencies"
          flutter pub get
          echo "::endgroup::"

      # Step 5: Build for Web
      - name: Build Flutter Web
        working-directory: Applicatie/Cross_Platform_Groep2
        run: |
          echo "::group::Building Flutter Web"
          flutter build web
          echo "::endgroup::"

      # Step 6: Verify Build Output
      - name: Verify Build Output
        working-directory: Applicatie/Cross_Platform_Groep2
        run: |
          echo "::group::Verifying Build Output"
          ls build/web
          echo "::endgroup::"
