name: Build Web Release

on:
  push:
    branches:
      - main

jobs:
  build-web:
    name: Build Web Release
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Step 3: Navigate to the Flutter app directory
      - name: Navigate to Flutter App Directory
        working-directory: Applicatie/Cross_Platform_Groep2
        run: echo "Navigating to Flutter app directory"

      # Step 4: Install dependencies
      - name: Install Flutter Dependencies
        working-directory: Applicatie/Cross_Platform_Groep2
        run: flutter pub get

      # Step 5: Build for Web
      - name: Build Flutter Web Application
        working-directory: Applicatie/Cross_Platform_Groep2
        run: flutter build web

      # Step 6: Verify Build Output
      - name: Verify Build Output
        working-directory: Applicatie/Cross_Platform_Groep2
        run: ls build/web
