name: Build Web Release

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  setup-flutter:
    name: Set up Flutter Environment
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

  build:
    name: Build Web Application
    runs-on: ubuntu-latest
    needs: setup-flutter

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter Dependencies
        working-directory: Applicatie/Cross_Platform_Groep2
        run: flutter pub get

      - name: Build Flutter Web Application
        working-directory: Applicatie/Cross_Platform_Groep2
        run: flutter build web
